// build-web.mjs — precompile the Orchis Foundry frontend.
//
// Transpiles the source JSX (served raw + Babel-in-browser during prototyping)
// into a single classic-script bundle, and vendors React's production UMD
// builds, so the shipped page loads no remote scripts and needs no in-browser
// transpiler. Run from the build/ dir (where node_modules lives):
//
//     cd build && npm run build
//
// Output (under web/, which is embedded into the binary):
//   web/app.bundle.js        concatenated, JSX-transpiled app
//   web/vendor/react*.js      pinned React 18 production UMD
//
// index.html (static) loads vendor/react, vendor/react-dom, then app.bundle.js.
// The source list below must match the original <script> order in index.html.

import { mkdirSync, copyFileSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const web = join(repo, "web");
const buildDir = join(repo, "build");

// @babel/core lives under build/node_modules; resolve it from there since this
// script sits in scripts/ (no node_modules of its own).
const requireFromBuild = createRequire(pathToFileURL(join(buildDir, "package.json")));
const { transformFileSync } = requireFromBuild("@babel/core");

// Load order — identical to the script tags index.html used during prototyping.
const SOURCES = [
  "tweaks-panel.jsx",
  "src/icons.jsx",
  "src/data.jsx",
  "src/palette.jsx",
  "src/sidebar.jsx",
  "src/views/dashboard.jsx",
  "src/views/repo.jsx",
  "src/views/pr.jsx",
  "src/views/devsettings.jsx",
  "src/app.jsx",
];

function buildBundle() {
  const parts = [
    "// AUTO-GENERATED by scripts/build-web.mjs — do not edit.",
    "// Source of truth: web/src/*.jsx. Rebuild with `cd build && npm run build`.",
    '"use strict";',
  ];
  for (const rel of SOURCES) {
    const abs = join(web, rel);
    const { code } = transformFileSync(abs, {
      presets: [[join(buildDir, "node_modules/@babel/preset-react"), { runtime: "classic" }]],
      babelrc: false,
      configFile: false,
      sourceMaps: false,
    });
    parts.push(`\n// ===== ${rel} =====\n${code}`);
  }
  const out = join(web, "app.bundle.js");
  writeFileSync(out, parts.join("\n"), "utf8");
  const bytes = Buffer.byteLength(parts.join("\n"));
  console.log(`wrote app.bundle.js (${(bytes / 1024).toFixed(1)} KB) from ${SOURCES.length} files`);
}

function vendorReact() {
  const vdir = join(web, "vendor");
  mkdirSync(vdir, { recursive: true });
  const files = [
    ["react/umd/react.production.min.js", "react.production.min.js"],
    ["react-dom/umd/react-dom.production.min.js", "react-dom.production.min.js"],
  ];
  for (const [src, dst] of files) {
    copyFileSync(join(buildDir, "node_modules", src), join(vdir, dst));
    console.log(`vendored ${dst}`);
  }
}

// Sanity: index.html must reference the bundle and vendored react, not unpkg.
function checkIndex() {
  const html = readFileSync(join(web, "index.html"), "utf8");
  const problems = [];
  if (html.includes("unpkg.com")) problems.push("index.html still references unpkg.com");
  if (html.includes("text/babel")) problems.push("index.html still uses type=text/babel");
  if (!html.includes("app.bundle.js")) problems.push("index.html does not load app.bundle.js");
  if (problems.length) {
    console.error("WARNING:\n  " + problems.join("\n  "));
  } else {
    console.log("index.html OK (no unpkg, no babel, loads app.bundle.js)");
  }
}

vendorReact();
buildBundle();
checkIndex();
console.log("done.");
